#!/bin/bash
# Get information about current git commit.
TAG=$(git describe --always --tag)
COMMIT=$(git log -1 --format="%H (%s | %ai)")
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Branch: ${BRANCH}"
echo "Tag: ${TAG}"
echo "Commit: ${COMMIT}"
